### ISSUE TITLE
Bug in negative number display...

### ISSUE THREAD

**Issue by gregdelozier** [dustinpoissant/jquery.dpNumberPicker#3]
Hi,

Working with your (very nice) number picker, and noticed it has trouble formatting negative numbers. 

May I humbly suggest that if you remove the sign from numbers and append the sign to the results, it works much better. 

Bug: Set step to 0.5 and step into negative numbers. You’ll get values like: -1.0, -2.5, -2.0, -3.5, -3.0

Proposed solution: 

```javascript

		function formatter(value, format){
			if(typeof(format) == "string" && format.length > 0){
				sign = ""
				if (value < 0) {
					value = -value;
					sign = "-"
				}
				var pos = format.indexOf(".");
				if (pos == -1){
					var before = Math.floor(value).toString();
					while(before.length < format.length) before = "0"+before;
					return sign + before;
				}
				var before = Math.floor(value).toString();
				while(before.length < pos) before = "0"+before;
				var after = Math.round((Math.round( Math.pow(10, (format.length-pos)-1) ))*(value-Math.floor(value))).toString();
				while(after.length < (format.length-pos)-1) after += "0";
				return sign + before + "."+after;
			} else return value;
		};
```

Notice the fact that all the formatting is now done on positive numbers, and then we restore the sign. 

Anyway, if you can use this, or have a better solution, that would be great. 

Best wishes, and thanks!

-greg

**Comment by dustinpoissant** [comment]
This repo has moved to http://github.com/addcms/addNumberPicker
