### ISSUE TITLE
Inconsistent call to "AfterChange"

### ISSUE THREAD

**Issue by gregdelozier** [dustinpoissant/jquery.dpNumberPicker#4]
Hi,

Little problem with the AfterChange event: 

Somewhere around line 123 we find this:

				if(changed){
					element.options.afterChange();
					if(increase) element.options.afterIncrease.call(element);
					else element.options.afterDecrease.call(element);
				}

This causes the "this" argument to the afterChange call to be something other than the usually expected element object when the value is changed by typing in a new number. 

It needs to be changed to 

				if(changed){
					element.options.afterChange.call(element);
					if(increase) element.options.afterIncrease.call(element);
					else element.options.afterDecrease.call(element);
				}

...to make that event call consistent. 

Anyway, thanks for a great product! 

Best wishes,

-greg

**Comment by dustinpoissant** [comment]
This repo has moved to http://github.com/addcms/addNumberPicker
